# Generated by Django 5.2.1 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='file_path',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_file',
            field=models.FileField(blank=True, null=True, upload_to='agent_files/'),
        ),
    ]
