"""
Django settings for ai_marketplace project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ # Import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is ai_marketplace/ai_marketplace/
# Project root (where manage.py is) is BASE_DIR.parent
# .env file will be at BASE_DIR.parent.parent if it's at the root of the whole multi-project repo
# Let's assume .env is at the Django project root (ai_marketplace/) for this setup
# So, BASE_DIR here is correct for where manage.py is.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    DJANGO_ALLOWED_HOSTS=(list, [])
)
# Read .env file from the Django project root (ai_marketplace/.env)
# This means the .env file should be inside the ai_marketplace directory,
# or adjust the path to BASE_DIR.parent / '.env' if .env is in the global project root.
# For docker-compose, env vars are passed directly, but for local dev .env is useful.
# Let's assume .env is at the level of manage.py, so BASE_DIR / '.env'
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env('DJANGO_SECRET_KEY', default='a_very_unsafe_default_secret_key_for_dev_only_change_it_if_no_env_var_is_set')

DEBUG = env('DEBUG') # Default is False from Env initialization

# Get ALLOWED_HOSTS from env var, split by space. Default to empty list.
# Example: DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 [::1] backend"
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])
# If running in Docker with Nginx proxy, 'backend' (service name) might be needed if requests come from there.
# Or, more commonly, configure Nginx to set X-Forwarded-Host and use USE_X_FORWARDED_HOST = True

# If your web server is behind a proxy (like Nginx in Docker Compose),
# these settings help Django understand the original request scheme and host.
USE_X_FORWARDED_HOST = True # If your proxy sets X-Forwarded-Host
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') # If your proxy sets X-Forwarded-Proto for https


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_marketplace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db_url(
        'DATABASE_URL', # e.g. postgresql://user:pass@host:port/dbname
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}"
    )
}
# Ensure the DATABASE_URL in .env or docker-compose environment matches this structure.
# Example for docker-compose: postgresql://admin:admin@db:5432/marketplace


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
